name: Build and deploy Node.js app to Azure Web App - nodejs-programmeren4-2324

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: Clean npm cache
              run: npm cache clean --force

            - name: Remove node_modules and package-lock.json
              run: |
                  rm -rf node_modules
                  rm -f package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Build the project
              run: npm run build --if-present

            - name: Zip artifact for deployment
              run: |
                  zip -r release.zip .
                  ls -la release.zip

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: release.zip

    integrationtests:
        runs-on: ubuntu-latest
        needs: build
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3
                env:
                    MYSQL_ROOT_PASSWORD: root
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Wait for MySQL to be ready
              run: |
                  until mysqladmin ping -h 127.0.0.1 --silent; do
                    echo 'Waiting for MySQL...'
                    sleep 1
                  done

            - name: Create and import database
              run: |
                  sudo apt-get update
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS share_a_meal;"
                  mysql -h 127.0.0.1 -uroot -proot share_a_meal < share-a-meal.create.sql
                  mysql -h 127.0.0.1 -uroot -proot share_a_meal < share-a-meal.sql

            - name: Clean npm cache and reinstall dependencies
              run: |
                  npm cache clean --force
                  rm -rf node_modules
                  rm -f package-lock.json
                  npm install

            - name: Install Mocha
              run: npm install mocha --save-dev

            - name: List node_modules
              run: ls -la node_modules

            - name: Run tests
              env:
                  DB_HOST: 127.0.0.1
                  DB_USER: root
                  DB_PASSWORD: root
                  DB_NAME: share_a_meal
                  DB_PORT: 3306
              run: |
                  npx mocha --timeout 5000 --DB_PASSWORD=root --DB_USER=root --DB_NAME=share_a_meal --DB_PORT=3306

    deploy:
        runs-on: ubuntu-latest
        needs: integrationtests
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C21D11036B54275804C7A2050A1A401 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63B2622D61A14A8DB0D9DFFF08D7E175 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6785D6D6937A49F58842568B15B1C07A }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: 'nodejs-programmeren4-2324'
                  slot-name: 'Production'
                  package: .
